spring.application.name=BD-CU
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost/BD_CU
spring.datasource.username=postgres
spring.datasource.password=postgres
